Refactor if statements

diff --git a/scripts/internal b/scripts/internal
--- a/scripts/internal
+++ b/scripts/internal
@@ -8,55 +8,45 @@
 # ------------------------------------------------------------------------------
 
 check_local_changes() {
-  if [ "$(git status --porcelain | wc -l)" -gt 0 ]; then
-    echo "Error: There are local changes in the working tree:"
-    git status --porcelain | sed -r "s|^(.*)$|\t\1|g"
-    echo "Please commit your changes or stash them first."
-    return 1
-  fi
-  return 0
+  [ "$(git status --porcelain | wc -l)" -eq 0 ] && return 0
+  echo "Error: There are local changes in the working tree:"
+  git status --porcelain | sed -r "s|^(.*)$|\t\1|g"
+  echo "Please commit your changes or stash them first."
+  return 1
 }
 
 check_remote_branch_exists() {
   local branch_name=$1
-  if [ "$(git branch --remote --list "$branch_name" | wc -l)" -eq 0 ]; then
-    echo "Error: Remote branch $branch_name does not exist."
-    echo "Aborted."
-    return 1
-  fi
-  return 0
+  [ "$(git branch --remote --list "$branch_name" | wc -l)" -gt 0 ] && return 0
+  echo "Error: Remote branch $branch_name does not exist."
+  echo "Aborted."
+  return 1
 }
 
 check_remote_branch_does_not_exist() {
   local branch_name=$1
-  if [ "$(git branch --remote --list "$branch_name" | wc -l)" -gt 0 ]; then
-    echo "Error: Remote branch $branch_name already exists."
-    echo "Aborted."
-    return 1
-  fi
-  return 0
+  [ "$(git branch --remote --list "$branch_name" | wc -l)" -eq 0 ] && return 0
+  echo "Error: Remote branch $branch_name already exists."
+  echo "Aborted."
+  return 1
 }
 
 check_remote_tag_does_not_exist() {
   local remote_name=$1
   local tag_name=$2
-  if [ "$(git ls-remote --tags "$remote_name" "$tag_name" | wc -l)" -gt 0 ]; then
-    echo "Error: Tag $tag_name already exists in remote $remote_name."
-    echo "Aborted."
-    return 1
-  fi
-  return 0
+  [ "$(git ls-remote --tags "$remote_name" "$tag_name" | wc -l)" -eq 0 ] && return 0
+  echo "Error: Tag $tag_name already exists in remote $remote_name."
+  echo "Aborted."
+  return 1
 }
 
 check_merge_conflict() {
   local branch_name=$1
   local flag_name=$2
-  if [ "$(git ls-files -u "$PROJECT_ROOT_DIR" | wc -l)" -gt 0 ]; then
-    echo "Error: Merge conflict detected while merging into $branch_name."
-    echo "Resolve conflicts and run $SCRIPT_PATH $TARGET_VERSION $DEVELOPMENT_VERSION $flag_name"
-    return 1
-  fi
-  return 0
+  [ "$(git ls-files -u "$PROJECT_ROOT_DIR" | wc -l)" -eq 0 ] && return 0
+  echo "Error: Merge conflict detected while merging into $branch_name."
+  echo "Resolve conflicts and run $SCRIPT_PATH $TARGET_VERSION $DEVELOPMENT_VERSION $flag_name"
+  return 1
 }
 
 # ------------------------------------------------------------------------------
@@ -86,9 +76,7 @@ merge_into_main() {
   git merge --no-ff --no-edit "$REMOTE_NAME/$BRANCH_PREFIX/$TARGET_VERSION"
   check_merge_conflict "$MAIN_BRANCH_NAME" "--continue-from-main"
   local return_value=$?
-  if [ $return_value -ne 0 ]; then
-    exit $return_value
-  fi
+  [ $return_value -ne 0 ] && exit $return_value
 }
 
 merge_into_development() {
@@ -101,9 +89,7 @@ merge_into_development() {
   git merge --no-ff --no-edit "$BRANCH_PREFIX/$TARGET_VERSION"
   check_merge_conflict "$DEVELOPMENT_BRANCH_NAME" "--continue-from-development"
   local return_value=$?
-  if [ $return_value -ne 0 ]; then
-    exit $return_value
-  fi
+  [ $return_value -ne 0 ] && exit $return_value
 }
 
 push_to_remote() {
@@ -118,29 +104,21 @@ push_to_remote() {
 start() {
   check_local_changes
   local return_value=$?
-  if [ $return_value -ne 0 ]; then
-    return $return_value
-  fi
+  [ $return_value -ne 0 ] && return $return_value
 
   git fetch "$REMOTE_NAME"
 
   check_remote_tag_does_not_exist "$REMOTE_NAME" "v$TARGET_VERSION"
   return_value=$?
-  if [ $return_value -ne 0 ]; then
-    return $return_value
-  fi
+  [ $return_value -ne 0 ] && return $return_value
 
   check_remote_branch_exists "$REMOTE_NAME/$BASE_BRANCH"
   return_value=$?
-  if [ $return_value -ne 0 ]; then
-    return $return_value
-  fi
+  [ $return_value -ne 0 ] && return $return_value
 
   check_remote_branch_does_not_exist "$REMOTE_NAME/$BRANCH_PREFIX/$TARGET_VERSION"
   return_value=$?
-  if [ $return_value -ne 0 ]; then
-    return $return_value
-  fi
+  [ $return_value -ne 0 ] && return $return_value
 
   git checkout -B "$BRANCH_PREFIX/$TARGET_VERSION" "$REMOTE_NAME/$BASE_BRANCH"
   change_version "$TARGET_VERSION"
@@ -182,35 +160,25 @@ finish() {
 
   check_local_changes
   local return_value=$?
-  if [ $return_value -ne 0 ]; then
-    return $return_value
-  fi
+  [ $return_value -ne 0 ] && return $return_value
 
   git fetch "$REMOTE_NAME"
 
   check_remote_tag_does_not_exist "$REMOTE_NAME" "v$TARGET_VERSION"
   return_value=$?
-  if [ $return_value -ne 0 ]; then
-    return $return_value
-  fi
+  [ $return_value -ne 0 ] && return $return_value
 
   check_remote_branch_exists "$REMOTE_NAME/$MAIN_BRANCH_NAME"
   return_value=$?
-  if [ $return_value -ne 0 ]; then
-    return $return_value
-  fi
+  [ $return_value -ne 0 ] && return $return_value
 
   check_remote_branch_exists "$REMOTE_NAME/$DEVELOPMENT_BRANCH_NAME"
   return_value=$?
-  if [ $return_value -ne 0 ]; then
-    return $return_value
-  fi
+  [ $return_value -ne 0 ] && return $return_value
 
   check_remote_branch_exists "$REMOTE_NAME/$BRANCH_PREFIX/$TARGET_VERSION"
   return_value=$?
-  if [ $return_value -ne 0 ]; then
-    return $return_value
-  fi
+  [ $return_value -ne 0 ] && return $return_value
 
   git tag -f "v$TARGET_VERSION" "$REMOTE_NAME/$BRANCH_PREFIX/$TARGET_VERSION"
   merge_into_main
