Organize helper functions

diff --git a/scripts/internal b/scripts/internal
--- a/scripts/internal
+++ b/scripts/internal
@@ -62,6 +62,48 @@ check_if_remote_tag_does_not_exist() {
   return 0
 }
 
+check_merge_conflict() {
+  local branch_name=$1
+  local flag_name=$2
+  if [ "$(git ls-files -u "$PROJECT_ROOT_DIR" | wc -l)" -gt 0 ]; then
+    echo "Error: Merge conflict detected while merging into $branch_name."
+    echo "Resolve conflicts and run $SCRIPT_PATH $TARGET_VERSION $DEVELOPMENT_VERSION $flag_name"
+    return 1
+  fi
+  return 0
+}
+
+merge_into_main() {
+  git checkout -B "$MAIN_BRANCH_NAME" "$REMOTE_NAME/$MAIN_BRANCH_NAME"
+  git pull --ff-only
+  git merge --no-ff --no-edit "$REMOTE_NAME/$BRANCH_PREFIX/$TARGET_VERSION"
+  check_merge_conflict "$MAIN_BRANCH_NAME" "--continue-from-main"
+  local return_value=$?
+  if [ $return_value -ne 0 ]; then
+    exit $return_value
+  fi
+}
+
+merge_into_development() {
+  git checkout -B "$BRANCH_PREFIX/$TARGET_VERSION" "$REMOTE_NAME/$BRANCH_PREFIX/$TARGET_VERSION"
+  git pull --ff-only
+  change_version "$DEVELOPMENT_VERSION"
+
+  git checkout -B "$DEVELOPMENT_BRANCH_NAME" "$REMOTE_NAME/$DEVELOPMENT_BRANCH_NAME"
+  git pull --ff-only
+  git merge --no-ff --no-edit "$BRANCH_PREFIX/$TARGET_VERSION"
+  check_merge_conflict "$DEVELOPMENT_BRANCH_NAME" "--continue-from-development"
+  local return_value=$?
+  if [ $return_value -ne 0 ]; then
+    exit $return_value
+  fi
+}
+
+push_to_remote() {
+  echo "Pushing to $REMOTE_NAME..."
+  git push "$REMOTE_NAME" "$MAIN_BRANCH_NAME" "$DEVELOPMENT_BRANCH_NAME" "$BRANCH_PREFIX/$TARGET_VERSION" "v$TARGET_VERSION"
+}
+
 # ------------------------------------------------------------------------------
 # Start
 # ------------------------------------------------------------------------------
@@ -96,48 +138,6 @@ start() {
 # ------------------------------------------------------------------------------
 # Finish
 # ------------------------------------------------------------------------------
-
-check_merge_conflict() {
-  local branch_name=$1
-  local flag_name=$2
-  if [ "$(git ls-files -u "$PROJECT_ROOT_DIR" | wc -l)" -gt 0 ]; then
-    echo "Error: Merge conflict detected while merging into $branch_name."
-    echo "Resolve conflicts and run $SCRIPT_PATH $TARGET_VERSION $DEVELOPMENT_VERSION $flag_name"
-    return 1
-  fi
-  return 0
-}
-
-push_to_remote() {
-  echo "Pushing to $REMOTE_NAME..."
-  git push "$REMOTE_NAME" "$MAIN_BRANCH_NAME" "$DEVELOPMENT_BRANCH_NAME" "$BRANCH_PREFIX/$TARGET_VERSION" "v$TARGET_VERSION"
-}
-
-merge_into_main() {
-  git checkout -B "$MAIN_BRANCH_NAME" "$REMOTE_NAME/$MAIN_BRANCH_NAME"
-  git pull --ff-only
-  git merge --no-ff --no-edit "$REMOTE_NAME/$BRANCH_PREFIX/$TARGET_VERSION"
-  check_merge_conflict "$MAIN_BRANCH_NAME" "--continue-from-main"
-  local return_value=$?
-  if [ $return_value -ne 0 ]; then
-    exit $return_value
-  fi
-}
-
-merge_into_development() {
-  git checkout -B "$BRANCH_PREFIX/$TARGET_VERSION" "$REMOTE_NAME/$BRANCH_PREFIX/$TARGET_VERSION"
-  git pull --ff-only
-  change_version "$DEVELOPMENT_VERSION"
-
-  git checkout -B "$DEVELOPMENT_BRANCH_NAME" "$REMOTE_NAME/$DEVELOPMENT_BRANCH_NAME"
-  git pull --ff-only
-  git merge --no-ff --no-edit "$BRANCH_PREFIX/$TARGET_VERSION"
-  check_merge_conflict "$DEVELOPMENT_BRANCH_NAME" "--continue-from-development"
-  local return_value=$?
-  if [ $return_value -ne 0 ]; then
-    exit $return_value
-  fi
-}
 
 finish() {
   if [ $# -gt 0 ]; then
