Check existence of remote tags/branches

diff --git a/scripts/internal b/scripts/internal
--- a/scripts/internal
+++ b/scripts/internal
@@ -31,6 +31,37 @@ check_local_changes() {
   return 0
 }
 
+check_if_remote_branch_exists() {
+  local branch_name=$1
+  if [ "$(git branch --remote --list "$branch_name" | wc -l)" -eq 0 ]; then
+    echo "Error: Remote branch $branch_name does not exist."
+    echo "Aborted."
+    return 1
+  fi
+  return 0
+}
+
+check_if_remote_branch_does_not_exist() {
+  local branch_name=$1
+  if [ "$(git branch --remote --list "$branch_name" | wc -l)" -gt 0 ]; then
+    echo "Error: Remote branch $branch_name already exists."
+    echo "Aborted."
+    return 1
+  fi
+  return 0
+}
+
+check_if_remote_tag_does_not_exist() {
+  local remote_name=$1
+  local tag_name=$2
+  if [ "$(git ls-remote --tags "$remote_name" "$tag_name" | wc -l)" -gt 0 ]; then
+    echo "Error: Tag $tag_name already exists in remote $remote_name."
+    echo "Aborted."
+    return 1
+  fi
+  return 0
+}
+
 # ------------------------------------------------------------------------------
 # Start
 # ------------------------------------------------------------------------------
@@ -43,11 +74,19 @@ start() {
   fi
 
   git fetch "$REMOTE_NAME"
-  if [ "$(git branch --remote --list "$REMOTE_NAME/$BRANCH_PREFIX/$TARGET_VERSION" | wc -l)" -gt 0 ]; then
-    echo "Error: Branch $REMOTE_NAME/$BRANCH_PREFIX/$TARGET_VERSION already exists."
-    echo "Aborted."
-    return 1
+
+  check_if_remote_branch_exists "$REMOTE_NAME/$BASE_BRANCH"
+  return_value=$?
+  if [ $return_value -ne 0 ]; then
+    return $return_value
   fi
+
+  check_if_remote_branch_does_not_exist "$REMOTE_NAME/$BRANCH_PREFIX/$TARGET_VERSION"
+  return_value=$?
+  if [ $return_value -ne 0 ]; then
+    return $return_value
+  fi
+
   git checkout -B "$BRANCH_PREFIX/$TARGET_VERSION" "$REMOTE_NAME/$BASE_BRANCH"
   change_version "$TARGET_VERSION"
   git push -u "$REMOTE_NAME" "$BRANCH_PREFIX/$TARGET_VERSION"
@@ -134,6 +173,31 @@ finish() {
   fi
 
   git fetch "$REMOTE_NAME"
+
+  check_if_remote_tag_does_not_exist "$REMOTE_NAME" "v$TARGET_VERSION"
+  return_value=$?
+  if [ $return_value -ne 0 ]; then
+    return $return_value
+  fi
+
+  check_if_remote_branch_exists "$REMOTE_NAME/$MAIN_BRANCH_NAME"
+  return_value=$?
+  if [ $return_value -ne 0 ]; then
+    return $return_value
+  fi
+
+  check_if_remote_branch_exists "$REMOTE_NAME/$DEVELOPMENT_BRANCH_NAME"
+  return_value=$?
+  if [ $return_value -ne 0 ]; then
+    return $return_value
+  fi
+
+  check_if_remote_branch_exists "$REMOTE_NAME/$BRANCH_PREFIX/$TARGET_VERSION"
+  return_value=$?
+  if [ $return_value -ne 0 ]; then
+    return $return_value
+  fi
+
   git tag -f "v$TARGET_VERSION" "$REMOTE_NAME/$BRANCH_PREFIX/$TARGET_VERSION"
   merge_into_main
   merge_into_development
